# Databricks notebook source
# MAGIC %md
# MAGIC #Notebook to create views 

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE WIDGET TEXT core_catalog DEFAULT "coreprod";
# MAGIC CREATE WIDGET TEXT catalog DEFAULT "";
# MAGIC CREATE WIDGET TEXT schema DEFAULT "";
# MAGIC CREATE WIDGET TEXT view_name DEFAULT "vw_trading_glossary";

# COMMAND ----------

# MAGIC %md
# MAGIC ###Copy widgets into local variables
# MAGIC Databricks has a bug clearing widgets values on a change. 
# MAGIC Following command is copying wdgets values into the local variable and removing widgets. 
# MAGIC

# COMMAND ----------

spark.conf.set ('widget.core_catalog', dbutils.widgets.get("core_catalog"))
spark.conf.set ('widget.catalog', dbutils.widgets.get("catalog"))
spark.conf.set ('widget.schema', dbutils.widgets.get("schema"))
spark.conf.set ('widget.view_name', dbutils.widgets.get("view_name"))


#Reset the widgets values to avoid any caching issues. 
dbutils.widgets.text('core_catalog', "")
dbutils.widgets.text('catalog', "")
dbutils.widgets.text('schema', "")
dbutils.widgets.text('view_name', "")
dbutils.widgets.removeAll()

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT '${widget.core_catalog}' AS core_catalog,
# MAGIC        '${widget.catalog}' AS catalog,
# MAGIC        '${widget.schema}' AS schema,
# MAGIC        '${widget.view_name}' AS view_name;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE VIEW ${widget.catalog}.${widget.schema}.${widget.view_name}
# MAGIC AS
# MAGIC (SELECT 'Daily' as table_name,	1 as row_number,	'Promotion Type' as column_name,	'Rewards promotion Type, e.g. Super Star Product' as column_description,	'Star and Super Star Products only' as comments
# MAGIC UNION SELECT 'Daily',	2,	'Category',	'Category description for the Asda Rewards campaign product', null
# MAGIC UNION SELECT 'Daily',	3,	'Department',	'Department name for the Asda Rewards campaign product', null 
# MAGIC UNION SELECT 'Daily',	4,	'Supplier',	'Supplier name for the Asda Rewards campaign product',	'vendor_nm in odl_dim_item_hierarchy'
# MAGIC UNION SELECT 'Daily',	5,	'Campaign Name',	'Promotion campaign name from the Asda Rewards cmpgn_setup table', null	 
# MAGIC UNION SELECT 'Daily',	6,	'Campaign ID',	'Promotion campaign ID from the Asda Rewards cmpgn_setup table',	'Primary campaign identifier'
# MAGIC UNION SELECT 'Daily',	7,	'Cash Pot Value',	'The cash pot value awarded when the campaign is redeemed. £ value for Superstar Products, "10%" for Star Products',	'Marvel Reporting Dashboard.Cmpgn_Setup.Pound_Value'
# MAGIC UNION SELECT 'Daily',	8,	'Campaign Start Date',	'Offical start date of the promotion from the Asda Rewards', 'cmpgn_setup table'	 
# MAGIC UNION SELECT 'Daily',	9,	'Campaign End Date',	'Offical end date of the promotion from the Asda Rewards cmpgn_setup table',	'Redemptions can occur after this date e.g. GHS'
# MAGIC UNION SELECT 'Daily',	10,	'Visit Date',	'Visit or transaction date for the record. This represents the scan date for all-Asda transactions and the campaign complete date for rewards redemptions', null	 
# MAGIC UNION SELECT 'Daily',	11,	'Rewards Participation',	'Percentage of EPOS items that generated a promotion redemption due to a Rewards barcode being scanned at the till',	'Rewards Redemption Volume / Total EPOS Volume'
# MAGIC UNION SELECT 'Daily',	12,	'Rewards Cash Pot',	'Total amount of rewards cashpot earn generated by promotion redemptions on the visit date', null 
# MAGIC UNION SELECT 'Daily',	13,	'Rewards Redemption Volume',	'Total number of promotion redemptions on the visit date at item level. All Asda channels and promotion EANs included', null
# MAGIC UNION SELECT 'Daily',	14,	'Total EPOS Volume',	'Total volume of items sold on the visit date that would qualify as a promotion redemption. All Asda channels and promotion EANs included', null 
# MAGIC UNION SELECT 'Daily',	15,	'Total EPOS Value',	'Total value (including VAT) of items sold on the visit date that would qualify as a promotion redemption. All Asda channels and promotion EANs included', null 
# MAGIC UNION SELECT 'Daily',	16,	'Rewards Redemption Customers',	'Redeemer Volume. Unique number of Asda Rewards wallet_ids that redeemed the promotion on the visit date', null	 
# MAGIC UNION SELECT 'Daily',	17,	'EPOS Customers',	'Proxy for unique number of Asda customers that purchased one or more promotion EANs on the visit date',	'Count of unique basket IDs'
# MAGIC UNION SELECT 'Daily',	18,	'Rewards Customer Participation',	'Percentage of EPOS customers that purchased the Star Product that also scanned and redeemed the promotion',	'Rewards Redemption Customers / EPOS Customers'
# MAGIC UNION SELECT 'Daily',	19,	'Rewards Scanned Customers',	'Total volume of customers that scanned their Asda Rewards barcode on the visit date', null	 
# MAGIC UNION SELECT 'Daily',	20,	'Rewards Customer Penetration',	'Percentage of customers that scanned their Asda Rewards barcode that also purchased the Star Product and redeemed the promotion on the visit date',	'Rewards Redemtpion Customers / Rewards Scanned Customers'
# MAGIC UNION SELECT 'Daily',	21,	'Rewards First Scan Customers',	'Number of customers that redeemed the promotion on their first time of scanning their Rewards barcode' ,null	 
# MAGIC UNION SELECT 'Daily',	22,	'Rewards First Scan %',	'Percentage of Rewards redeemers that were also first scan customers',	'Rewards First Scan Customers / Rewards Redemption Customers'
# MAGIC UNION SELECT 'Daily',	23,	'Prime WIN',	'Primary promotion WIN from item hierarchy table (all_links_item_number).', 'Primary WINs for promotions with multiple WINs can be found in the Campaign Lookup page'
# MAGIC UNION SELECT 'Summary',	1,	'Promotion Type',	'Rewards promotion Type, e.g. Super Star Product',	'Star and Super Star Products only'
# MAGIC UNION SELECT 'Summary',	2,	'Category',	'Category description for the Asda Rewards campaign product', null	 
# MAGIC UNION SELECT 'Summary',	3,	'Department',	'Department name for the Asda Rewards campaign product', null 
# MAGIC UNION SELECT 'Summary',	4,	'Supplier',	'Supplier name for the Asda Rewards campaign product',	'vendor_nm in odl_dim_item_hierarchy'
# MAGIC UNION SELECT 'Summary',	5,	'Campaign Name',	'Promotion campaign name from the Asda Rewards cmpgn_setup table', null	 
# MAGIC UNION SELECT 'Summary',	6,	'Campaign ID',	'Promotion campaign ID from the Asda Rewards cmpgn_setup table',	'Primary campaign identifier'
# MAGIC UNION SELECT 'Summary',	7,	'Cash Pot Value',	'The cash pot value awarded when the campaign is redeemed. £ value for Superstar Products, "10%" for Star Products', 'bi_data_model.Cmpgn_Setup.Pound_Value'
# MAGIC UNION SELECT 'Summary',	8,	'Campaign Start Date',	'Offical start date of the promotion from the Asda Rewards cmpgn_setup table', null	 
# MAGIC UNION SELECT 'Summary',	9,	'Campaign End Date',	'Offical end date of the promotion from the Asda Rewards cmpgn_setup table', null	 
# MAGIC UNION SELECT 'Summary',	10,	'Rewards Participation',	'Percentage of EPOS items that generated a promotion redemption due to a Rewards barcode being scanned at the till',	'Rewards Redemption Volume / Total EPOS Volume'
# MAGIC UNION SELECT 'Summary',	11,	'Rewards Cash Pot',	'Total amount of rewards cashpot earn generated by promotion redemptions during the whole campaign', null
# MAGIC UNION SELECT 'Summary',	12,	'In-Campaign Redemptions',	'Total volume of promotion redemptions that occurred during the official campaign period', null	 
# MAGIC UNION SELECT 'Summary',	13,	'In-Campaign EPOS Items',	'Total volume of EPOS items that were sold by Asda during the official campaign period', null
# MAGIC UNION SELECT 'Summary',	14,	'Rewards Customer Penetration',	'Percentage of customers that scanned their Asda Rewards barcode that also purchased the Star Product and redeemed the promotion during the official campaign period',	'Does not change with visit date filter, whole campaign shown'
# MAGIC UNION SELECT 'Summary',	15,	'Unique Redeemers',	'The volume of unique wallet_ids that redeemed the promtion during the campaign period', null
# MAGIC UNION SELECT 'Summary',	16,	'Unique Rewards Scanners',	'The volume of unique wallet_ids that scanned their Rewards barcode during the campaign period', null
# MAGIC UNION SELECT 'Summary',	17,	'Prime WIN',	'Primary promotion WIN from item hierarchy table (all_links_item_number). Primary WINs for promotions with multiple WINs can be found in the Campaign Lookup page', null
# MAGIC UNION SELECT 'Missions',	1,	'Promotion Type',	'Asda Rewards continuity promotion Type, e.g. Accumulator', null
# MAGIC UNION SELECT 'Missions',	2,	'Campaign Name',	'Promotion campaign name from the Asda Rewards cmpgn_setup table', null
# MAGIC UNION SELECT 'Missions',	3,	'Campaign ID',	'Promotion campaign ID from the Asda Rewards cmpgn_setup table', null
# MAGIC UNION SELECT 'Missions',	4,	'Campaign Start Date',	'Offical start date of the promotion from the Asda Rewards cmpgn_setup table', null
# MAGIC UNION SELECT 'Missions',	5,	'Campaign End Date',	'Offical end date of the promotion from the Asda Rewards cmpgn_setup table', null
# MAGIC UNION SELECT 'Missions',	6,	'Mission Status',	'Flag to show whether the promotion is currently active or expired',	'GHS redemptions can occur outside this period'
# MAGIC UNION SELECT 'Missions',	7,	'Mission Value',	'Cash pot earn value for completing the mission', null
# MAGIC UNION SELECT 'Missions',	8,	'Mission Spend Threshold',	'Amount the customer must spend within the Mission in order to complete it and earn the cash pot amount. Blank for visit / item threshold campaigns',	'gb_customer_data_domain_odl.cdd_odl_cmpgn_setup.trans_needed_reward_pnt_qty'
# MAGIC UNION SELECT 'Missions',	9,	'Missions Base (Allocated)',	'Volume of unique customers that were allocated the mission. Targeted customer base',	'Customers can only receive or complete the mission once'
# MAGIC UNION SELECT 'Missions',	10,	'Missions Seen (Delivered)',	'Volume of unique customers that were allocated the mission AND scanned their rewards barcode during the official campaign period',	'Mission reach.'
# MAGIC UNION SELECT 'Missions',	11,	'Missions Progressed (Started)',	'Volume of unique customers that progressed the mission by scanning their rewards barcode on a qualifying transaction',	'Customer has bought within the mission parameters'
# MAGIC UNION SELECT 'Missions',	12,	'Missions Completed (Redeemed)',	'Volume of unique customers that completed / redeemed the mission and earned the cash pot bonus', null
# MAGIC UNION SELECT 'Missions',	13,	'Progress Penetration Rate',	'Percentgage of unique customers that saw the mission during the campaign period and went on to progress within it',	'Missions Progressed (Started) /Missions, Seen, (Delivered)'
# MAGIC UNION SELECT 'Missions',	14,	'Mission Penetration Rate',	'Percentage of unique customers that saw the mission dring the campaign period and went on to complete it',	'Missions Completed (Redeemed) / Missions Seen (Delivered)'
# MAGIC UNION SELECT 'Missions',	15,	'Completed / Progressed Rate',	'Percentage of unique customers that progressed the mission that went on to complete it',	'Missions Completed (Redeemed) / Missions Progressed (Started)'
# MAGIC UNION SELECT 'Missions',	16,	'Rewards Cash Pot Earned',	'Total amount of rewards cashpot earn generated by promotion redemptions',	'Missions completed x Mission Value'
# MAGIC UNION SELECT 'Missions',	17,	'Delivered / Created Rate',	'Percentage of unique customers that were allocated the mission that scanned their rewards barcode during the official campaign period and presumably saw the mission',	'Missions Seen (Delivered) / Missions Base (Allocated)'
# MAGIC UNION SELECT 'Missions',	18,	'Progressed / Delivered Rate',	'Percentage of unique customers that saw the mission that progressed the mission',	'Missions Progressed (Started) / Missions Seen (Delivered)'
# MAGIC ORDER BY table_name, row_number)
